# Generated by Django 5.2.7 on 2025-10-09 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0002_bankaccount_bankcard_credit_deposit_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('iis', 'Индивидуальный инвестиционный счет'), ('pif', 'Паевой инвестиционный фонд'), ('brokerage', 'Брокерский счет'), ('trust', 'Доверительное управление')], max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20)),
                ('expected_return', models.DecimalField(decimal_places=2, help_text='Ожидаемая доходность в %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Активная'), ('sold', 'Проданная'), ('closed', 'Закрытая')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='dbo.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbo.investmentproduct')),
            ],
        ),
    ]
