# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0003_investmentproduct_clientinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('suspended', 'Приостановлена'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ежемесячная плата за услугу', max_digits=10),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Дата следующего платежа', null=True),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='auto_renewal',
            field=models.BooleanField(default=True, help_text='Автоматическое продление'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительные заметки'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_services', to='auth.user'),
        ),
    ]
