# Generated by Django 5.2.7 on 2025-12-09 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0003_add_service_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBOLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('client_created', 'Создание клиента'), ('client_updated', 'Обновление данных клиента'), ('transaction_created', 'Создание транзакции'), ('transaction_completed', 'Завершение транзакции'), ('service_connected', 'Подключение услуги'), ('service_disconnected', 'Отключение услуги'), ('service_request_created', 'Создание заявки на услугу'), ('service_request_approved', 'Одобрение заявки на услугу'), ('service_request_rejected', 'Отклонение заявки на услугу'), ('card_created', 'Создание карты'), ('card_pin_changed', 'Изменение PIN карты'), ('deposit_created', 'Создание депозита'), ('credit_created', 'Создание кредита'), ('investment_created', 'Создание инвестиции'), ('page_viewed', 'Просмотр страницы'), ('data_exported', 'Экспорт данных'), ('other', 'Прочее')], max_length=50, verbose_name='Тип события')),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('critical', 'Критическая ошибка')], default='info', max_length=20, verbose_name='Уровень важности')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
            ],
            options={
                'verbose_name': 'Лог ДБО',
                'verbose_name_plural': 'Логи ДБО',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AttackLog',
        ),
        migrations.AddField(
            model_name='client',
            name='is_privileged',
            field=models.BooleanField(default=False, help_text='Может подключать служебные услуги', verbose_name='Служебный клиент'),
        ),
        migrations.AddField(
            model_name='dbolog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbo.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='dbolog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbo.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='dbolog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='dbolog',
            index=models.Index(fields=['-created_at'], name='dbo_dbolog_created_24c7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='dbolog',
            index=models.Index(fields=['event_type'], name='dbo_dbolog_event_t_306e81_idx'),
        ),
        migrations.AddIndex(
            model_name='dbolog',
            index=models.Index(fields=['user'], name='dbo_dbolog_user_id_c8dd79_idx'),
        ),
        migrations.AddIndex(
            model_name='dbolog',
            index=models.Index(fields=['client'], name='dbo_dbolog_client__8e10a7_idx'),
        ),
    ]
