# Generated by Django 5.2.7 on 2025-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0004_clientservice_enhanced'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новости')),
                ('content', models.TextField(verbose_name='Содержание новости')),
                ('category', models.CharField(choices=[('general', 'Общие новости'), ('rates', 'Курсы валют'), ('promotions', 'Акции и предложения'), ('security', 'Безопасность'), ('services', 'Новые услуги')], default='general', max_length=50, verbose_name='Категория')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
