# Generated by Django 5.2.7 on 2025-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbo', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='service',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
